### ISSUE TITLE
做一个友联的页面吧

### ISSUE THREAD

**Issue by ihuanx** [guiqiqi/chromate#1]

**Comment by guiqiqi** [comment]
谢谢意见。

不知道你想要的友情链接页面是什么样子的，因为可以通过新建页面中填写友情链接来实现。
如果你有好的示例，可以放几个链接，我会去看一下，有可能的话在后期添加更新。

**Comment by guiqiqi** [comment]
已经进入开发日程，将伴随下个版本发布。
