### ISSUE TITLE
网页播放器 error

### ISSUE THREAD

**Issue by Lyunvy** [guiqiqi/chromate#11]
控制台报错：
`Uncaught TypeError: Shikwasa.use is not a function`
看 Shikwasa README 是更改了用法
https://github.com/jessuni/shikwasa/commit/61a356b9893ba61d5b415c02e10476dd11d861a9

**Comment by guiqiqi** [comment]
正在确认问题。
Confirming issue.

**Comment by guiqiqi** [comment]
问题已确认。（很抱歉之前忘了这件事。）
Issued confirmed.

**Comment by guiqiqi** [comment]
问题已修复。见 [v0.03](https://github.com/guiqiqi/chromate/tree/v0.0.3)。
Issued fixed. See [v0.03](https://github.com/guiqiqi/chromate/tree/v0.0.3).
