### ISSUE TITLE
这部分不晓得如何操作

### ISSUE THREAD

**Issue by ihuanx** [guiqiqi/chromate#2]
![](http://img03.sogoucdn.com/app/a/100520146/d96898cde0383a911c6722a7bb122013)

这个部分不知道怎么写 我把我的博文贴进去 ，他就展示所有内容了，感觉很不优雅，这一块应该是一个预览位

然后```代码块``` 会居中 显示错误

**Comment by guiqiqi** [comment]
0. 关于文章摘要生成
这不是一个 Bug。
请首先阅读：https://hexo.io/zh-cn/docs/tag-plugins#文章摘要和截断
这是 Hexo 官网的说明文档，使用 Hexo 的作者在写作前应该要阅读其中的内容：任何文章的 Excerpt 应该以 `<!--more-->` 与文章 Content 进行分割。

1. 关于代码块显示的错误
没有看到有错误的详细说明。
在发布 Issue 之前，请参考 Issue 模板 提供必要的信息以便 Debug。
