### ISSUE TITLE
关于时间轴重置的问题，谢谢！

### ISSUE THREAD

**Issue by vlalamoon** [guiqiqi/chromate#6]
您好，在使用的过程中发现一个问题就是设置时间轴后，在阅读博客的时候，点击任何一个划分好的时间节点，都会重置到播客的第一秒开始播放，请问是什么原因呢

**Comment by vlalamoon** [comment]
我大概了解是什么原因了
经过测试发现之前的mp3是和播客源文件保存在一起引用相对路径，会产生这样的bug
我把mp3上传到网端，引用mp3的外链就不会有了
或许还有别的原因？？？？

**Comment by guiqiqi** [comment]
Confirming Issue.

**Comment by guiqiqi** [comment]
感谢反馈。经过确认，这是一个存在的Bug，将在下面的 Commits 中修复。

*另：最近想休息一下，可能会更新较慢 :)*

**Comment by guiqiqi** [comment]
经过修复，在该 [Commit](https://github.com/guiqiqi/chromate/commit/23ead76b3eafd3ab033aa7507b6620962a1be3ae) 中已经解决了该问题。

但需要注意的是，如果你的音频分发服务器无法正确处理 Metadata 请求的话，播放器会显示为 **live** 模式，此时 Chapters 相关设置会失效。

这个 Patch 会在下个版本中一同 Release。
